sudo: required
services:
    - docker
    
before_install:
    - docker build -t gauravdhim1990/frontend -f Dockerfile.dev .
    
script:
    - docker run gauravdhim1990/frontend npm run test -- --coverage